import { NextApiRequest, NextApiResponse } from "next";

export default function (req: NextApiRequest, res: NextApiResponse) {
    res.status(200).json([
        {
            id: "1",
            name: "Name One",
            surname: "Surname One",
            dateOfBirth: "01-01-1991",
            position: "Position One",
            phoneNumber: "+994511111",
        },
        {
            id: "2",
            name: "Name Two",
            surname: "Surname Two",
            dateOfBirth: "02-02-1992",
            position: "Position Two",
            phoneNumber: "+994511112",
        },
        {
            id: "3",
            name: "Name Three",
            surname: "Surname Three",
            dateOfBirth: "03-03-1993",
            position: "Position Three",
            phoneNumber: "+994511113",
        },
        {
            id: "4",
            name: "Name Four",
            surname: "Surname Four",
            dateOfBirth: "04-04-1994",
            position: "Position Four",
            phoneNumber: "+994511114",
        },
        {
            id: "5",
            name: "Name Five",
            surname: "Surname Five",
            dateOfBirth: "05-05-1995",
            position: "Position Five",
            phoneNumber: "+994511115",
        },
        {
            id: "6",
            name: "Name Six",
            surname: "Surname Six",
            dateOfBirth: "06-06-1996",
            position: "Position Six",
            phoneNumber: "+994511116",
        },
        {
            id: "7",
            name: "Name Seven",
            surname: "Surname Seven",
            dateOfBirth: "07-07-1997",
            position: "Position Seven",
            phoneNumber: "+994511117",
        },
        {
            id: "8",
            name: "Name Eight",
            surname: "Surname Eight",
            dateOfBirth: "08-08-1998",
            position: "Position Eight",
            phoneNumber: "+994511118",
        },
        {
            id: "9",
            name: "Name Nine",
            surname: "Surname Nine",
            dateOfBirth: "09-09-1999",
            position: "Position Eight",
            phoneNumber: "+994511119",
        },
        {
            id: "10",
            name: "Name Ten",
            surname: "Surname Ten",
            dateOfBirth: "10-10-2000",
            position: "Position Ten",
            phoneNumber: "+994511120",
        },
        {
            id: "11",
            name: "Name Eleven",
            surname: "Surname Eleven",
            dateOfBirth: "11-11-2001",
            position: "Position Eleven",
            phoneNumber: "+994511121",
        },
        {
            id: "12",
            name: "Name Twelve",
            surname: "Surname Twelve",
            dateOfBirth: "12-12-2002",
            position: "Position Twelve",
            phoneNumber: "+994511122",
        },
    ]);
}
